# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: traumdiver's blog
email: traumdiver@gmail.com
description: Dev blog by traumdiver.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://traumdiver.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pmarsceill/just-the-docs

# Footer content
footer_content: "&copy; 2022. traumdiver all rights reserved."

# Color scheme supports "light" (default) and "dark"
color_scheme: default

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-83855303-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)